"""Compatibility imports for shared print placement."""
from mtg_print.layout import (
    copies,
    cells,
    fits,
    validate_capacity,
    first_space,
    record,
    resolve,
    move,
    pages_from_items,
    occupancy,
    occupancy_label,
    LayoutHistory,
    distribute_cards_to_pages,
    make_backside_pages,
    make_render_page_sequence,
    distribute_cards_to_grid,
    get_grid_coords,
)
